services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    volumes:
      - ./data/reglamento-de-estudiantes-universidad-javeriana.pdf:/app/reglamento.pdf
    depends_on:
      - qdrant
    restart: on-failure

volumes:
  qdrant_data:
